Create Calendar
js-tasks-ru/htmlcss-20230124_guliev pull request #11
Opened 2023-02-13 19:38 UTC by GulievAnar31

2023-02-13 19:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 10:27 UTC, GSemikozov requested changes

2023-02-14 10:27 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +            <div class="calendar__months">
calendar__week-days

2023-02-14 10:27 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +                <li class="calendar__month">Mon</li>
calendar__week-day

2023-02-14 13:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 13:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-14 13:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-14 18:32 UTC, GSemikozov approved these changes

2023-02-14 18:33 UTC, merged