MainPage with media breakpoints
js-tasks-ru/htmlcss-20230124_guliev pull request #13
Opened 2023-02-18 16:18 UTC by GulievAnar31

2023-02-18 16:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-18 16:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-20 15:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-20 15:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-20 15:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-21 08:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-21 09:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-23 22:15 UTC, GSemikozov requested changes

2023-02-23 22:15 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip_card {
удалим, лишнее

2023-02-23 22:15 UTC, GSemikozov commented on components/card/card.css
> +    margin-bottom: 12px;
если хотим встраиваемый компонент разместить вертикально по центру - нужно задать соответствующие стили

2023-02-27 13:01 UTC, GSemikozov requested changes

2023-02-27 13:01 UTC, GSemikozov commented on components/card/card.css
> +    padding-top: 45%;
а какую задачу решаем паддинг на половину высоты элемента?)
нужно просто выравнивать по середине: `display: flex; flex-direction: column; align-items: center; justify-content: center;`

2023-03-01 21:51 UTC, GSemikozov approved these changes

2023-03-01 21:51 UTC, merged