Create Radio
js-tasks-ru/htmlcss-20230124_guliev pull request #18
Opened 2023-02-25 17:04 UTC by GulievAnar31

2023-02-25 17:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-27 13:06 UTC, GSemikozov requested changes

2023-02-27 13:06 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    border-radius: 14px;
лишнее

2023-02-27 13:06 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    /* background: var(--blue-btn);
не актуально?

2023-02-27 18:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-27 18:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-27 18:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-01 21:50 UTC, GSemikozov approved these changes

2023-03-01 21:51 UTC, merged