create 3 buttons
js-tasks-ru/htmlcss-20230124_guliev pull request #4
Opened 2023-02-02 21:01 UTC by GulievAnar31

2023-02-02 21:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-03 13:56 UTC, GSemikozov requested changes

2023-02-03 13:56 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +button {
.button

2023-02-03 13:56 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
ширину жестко ограничивать не надо, простейшая ситуация когда верстка сломается - длинный текст

2023-02-03 13:56 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
не хватает паддингов

2023-02-03 13:56 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background: #2342C0;
достаточно opacity, + надо добавить pointer-events: none. И тогда - это состояние будет общим для всех кнопок, можно будет задать 1 раз через .button:disabled

2023-02-03 13:56 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +            <button class="button_primary">
модификатор нельзя использовать без того ЧТО он модифицирует - class="button button_primary"

2023-02-03 13:56 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +                <span class="button__title">
лишний вложенный элемент

2023-02-06 11:42 UTC, GSemikozov requested changes

2023-02-06 11:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import url('../../assets/css/main.css');
не нужно импортировать общий файл стилей в файл стилей блока - все делается наоборот

2023-02-06 11:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 0 14px;
слева-справа - 15

2023-02-06 11:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.card__button {
элемент блока card? здесь описываем блок .button, а не .card, и в целом это лишние стили - удалим

2023-02-06 11:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_alternate:disabled {
выше уже есть общий стиль для этого состояния

2023-02-06 12:27 UTC, GSemikozov requested changes

2023-02-06 12:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 100%;
лишнее, удалим

2023-02-07 08:46 UTC, GSemikozov requested changes

2023-02-07 08:46 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 15px 15px 14px;
`padding: 15px 15px 14px 15px;` ))

2023-02-07 10:30 UTC, GSemikozov approved these changes

2023-02-07 10:31 UTC, merged