Histogram
js-tasks-ru/htmlcss-20230124_guliev pull request #7
Opened 2023-02-08 13:31 UTC by GulievAnar31

2023-02-08 13:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-08 14:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-08 21:49 UTC, GSemikozov requested changes

2023-02-08 21:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
лишнее

2023-02-08 21:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    font-size: 2vw;
лучше в пикселях, иначе неясно какой здесь размер шрифта

2023-02-08 21:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 20px;
марджины на уровне блока не задаем

2023-02-08 21:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 1rem;
в процентах. И ниже

2023-02-08 21:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    display: inline-flex;
лишнее

2023-02-08 21:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
лишнее

2023-02-08 21:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    display: inline-flex;
а вот что надо - так это height: 50%

2023-02-08 21:49 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <p>View all</p>
это ссылка, то есть `<a>`

2023-02-08 21:49 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <p>View all</p>
на нее - класс histogram__link

2023-02-08 21:49 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__button">
лишний элемент

2023-02-09 12:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-09 12:47 UTC, GulievAnar31 commented on 04-lection2/01-histogram/histogram.css
> +    display: inline-flex;
Без display inline flex, контент распологается в колонку

2023-02-09 12:47 UTC, GulievAnar31 commented on 04-lection2/01-histogram/histogram.css
> +    height: 1rem;
В процентах не срабатывает почему то, сделал в пикселях

2023-02-09 13:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-09 13:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 1rem;
ответил в дискорде) все сработает, просто надо правильно оформить - процент работает относительно родителя, соответственно родителю надо высоту задать как 50px, и тогда высота колонок в процентах будет высчитываться от этого значения 50px = 100%

2023-02-09 13:41 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    display: inline-flex;
display: flex расположит элементы в один ряд по умолчанию. А вот высота должна быть 50px, я не ту единицу измерения указал (

2023-02-09 13:42 UTC, GSemikozov requested changes

2023-02-09 13:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 20%;
в дизайне это как flex-basis: 9px

2023-02-09 13:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 10px;
тут и ниже - в процентах

2023-02-09 13:42 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <p>Total orders</p>
вот эти два текстовых элемента не стилизованы остались

2023-02-09 14:34 UTC, GSemikozov requested changes

2023-02-09 14:34 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    display: inline-flex;
display: flex

2023-02-10 10:54 UTC, GSemikozov requested changes

2023-02-10 10:54 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: center;
лишнее

2023-02-10 10:54 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
тут высоту не стоит указывать, мы это делаем через модификаторы. Видимо это лишнее, рудимент

2023-02-10 10:54 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__link {
если линк наследует текст, и просто добавляет / меняет некоторые свойства - тогда лучше оформить как модификатор текста .histogram__text_link

2023-02-10 11:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-10 11:29 UTC, GSemikozov approved these changes

2023-02-10 11:29 UTC, merged