Add Skeleton
js-tasks-ru/htmlcss-20230124_guliev pull request #8
Opened 2023-02-09 13:49 UTC by GulievAnar31

2023-02-09 13:59 UTC, GSemikozov requested changes

2023-02-09 13:59 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 172px;
ширину в процентах

2023-02-09 13:59 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 257px;
и тут

2023-02-09 14:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-09 14:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-09 14:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-10 09:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-10 09:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-10 09:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-10 10:54 UTC, GSemikozov approved these changes

2023-02-10 10:54 UTC, merged